### PR TITLE
[enhancement] DRPC Image Support 

### PR DESCRIPTION
**Pull request by thororen1234**
I changed the discord rpc to have navidrome and jellyfin using the currentSong?.imageUrl and I changed the interval from 15 to 10.

### CODE REVIEW

**Comment by iiPythonx** [comment]
Assuming I'm reading it right, this no longer respects `discordSettings.showServerImage`, which it seems like it should; some people may not wish to have images on their status.

Additionally, this will still only work if the server URL Feishin is using is publicly accessible, so out of curiosity, what's the point of always sending it to discord? For anybody using a local media server (me included) no image will show up at all, not even the fallback icon.

**Comment by jeffvli** [comment]
Navidrome (and Subsonic) requires your credentials on the image URL so exposing that to Discord will potentially leak your username and password.

**Comment by thororen1234** [comment]
> Assuming I'm reading it right, this no longer respects `discordSettings.showServerImage`, which it seems like it should; some people may not wish to have images on their status.
> 
> Additionally, this will still only work if the server URL Feishin is using is publicly accessible, so out of curiosity, what's the point of always sending it to discord? For anybody using a local media server (me included) no image will show up at all, not even the fallback icon.

That was my bad I accidentally deleted it because mobile select sucks.

It should work on local servers because it would use the url of the image through your pc discord just uses the url it's given.

**Comment by thororen1234** [comment]
> Navidrome (and Subsonic) requires your credentials on the image URL so exposing that to Discord will potentially leak your username and password.

This is a very valid point I think some sort of tinkering is in place.

**Comment by iiPythonx** [comment]
> discord just uses the url it's given.

Last time I checked, all images that go through discord (rpc included) have to go through discord's proxy layer first. Because of that, sending a local URL to discord will just result in the image not loading, regardless of who tries to view it.

Pretty sure they do it this way to prevent things such as getting ip logged just from receiving an image.
Regardless, Feishin would need to upload the images to a service such as imgur in order to get them to display.

**Comment by thororen1234** [comment]
> > discord just uses the url it's given.
> 
> Last time I checked, all images that go through discord (rpc included) have to go through discord's proxy layer first. Because of that, sending a local URL to discord will just result in the image not loading, regardless of who tries to view it.
> 
> Pretty sure they do it this way to prevent things such as getting ip logged just from receiving an image. Regardless, Feishin would need to upload the images to a service such as imgur in order to get them to display.

That's dumb if so because the RPC server itself is locally hosted so says discord.

**Comment by thororen1234** [comment]
Anyways I'll come back when this is completely secure and such.

**Comment by kgarner7** [comment]
Consider following (or even contributing) on https://github.com/opensubsonic/open-subsonic-api/discussions/25 for better auth

**Pull request closed without merging**
