### PR TITLE
Ignore CORS

### LINKED ISSUE #14: Option to ignore certificate legitimacy
### What am I trying to achieve? 
I want to access a local navidrome server which is secured by a selfsigned certificate.

image

 The same happens when using mismatching certificates (Domain differs from certificate domain).

### How could it be solved?
Adding an option to accepts self signed certificates (This is how i use it in a mobile app [Ultrasonic](https://gitlab.com/ultrasonic/ultrasonic))

### Whats the impact of not solving this?
The app remains unusable without publicly exposing the server or doing some nasty workarounds with host files.

### PR DESCRIPTION
**Pull request by jeffvli**

### CODE REVIEW

**Comment by jeffvli** [comment]
@lennartbrandin I've pushed some additional changes which I believe may fix the CORS issue. Can you try the updated build?

**Comment by lennartbrandin** [comment]
Using the linux-binaries.zip that the github-actions bot linked. (I assume them up to date because it updated a few hours ago)

I did not notice any different behavior than mentioned [before](https://github.com/jeffvli/feishin/issues/14#issuecomment-1418854565).

**Comment by jeffvli** [comment]
Hmm.. I'm not sure why it's not working.

For reference, this is what's currently being applied:

1. `webSecurity: false` in the electron browser window web preferences.
2. Setting the fetch `mode` to `cors`

I did a bit of testing of my side albeit without using a self signed certificate but it seemed to ignore properly ignore CORS. I'll try some additional testing when I have the chance.

**Comment by lennartbrandin** [comment]
Screenshots from the debugging tool.
Screenshot from 2023-02-08 21-23-05
Screenshot from 2023-02-08 21-24-29

I've seen [mentions](https://stackoverflow.com/a/50419166) of using an [ignore certificate errors](https://www.electronjs.org/docs/latest/api/command-line-switches#--ignore-certificate-errors) switch in addition to webPreference settings.
*(Note that i've no/little experience using electron/ts)*

**Comment by jeffvli** [comment]
Thanks for that info!
I've pushed another change that adds an additional "Ignore SSL" toggle in the server list.

Let me know how that goes after the publish build finishes.

**Comment by lennartbrandin** [comment]
I can confirm that this works, both for self signed certificates, as for domain mismatching certificates.
*(Note that your auto updating feature may irritate when testing a unstable binary and it "updates" to the latest official release)*

**Comment by jeffvli** [comment]
I'll add an additional toggle to disable automatic updates in a later pr.

**Comment by redthing1** [comment]
I still seem to be having CORS issues in my client though

**Comment by lennartbrandin** [comment]
Please try to provide more information about what you tried, what happend, what you expect would happen, and if possible logs/webconsole output.

**Comment by redthing1** [comment]
Is the web console on in production builds? How do I open it? If not I'll get back to you from running the dev version later

**Comment by jeffvli** [comment]
Ctrl + Shift + I or there's a menu option in the file menu to open the web devtools.

**Comment by redthing1** [comment]
Screenshot 2023-12-08 at 7 46 49 PM


Well, i'm on Feishin v0.5.2, and with the switch on^ (obviously I restarted)

Screenshot 2023-12-08 at 7 47 22 PM

**Comment by jeffvli** [comment]
I need more details like:
- What server are you using? (Navidrome or Jellyfin)
- Running the web or desktop version? (I'm assuming desktop here)
- Are all the API requests failing, and if not which ones are failing?
- Is your server being accessed behind a reverse proxy?
- If yes to the above, does switching to the private URL resolve the issue?

**Comment by redthing1** [comment]
- Jellyfin
- Desktop
- Other API requests (fetching album data, etc.) work fine, and our web frontend works fine. What's failing is specifically album covers 
- Server is behind a reverse proxy. Accessing the private URL is not feasible in this case.

**Comment by redthing1** [comment]
Sadly, still appears to be broken on the latest version. I will investigate using the debug inspector at some point.

**Pull request merged**
