### PR TITLE
Add subsonic server support

### LINKED ISSUE #306: [Essential] Subsonic API Support
**Why Feishin does need the Subsonic API Now?**
As previously mentioned [over here](https://github.com/jeffvli/feishin/issues/289) there is an essential need to enable the Subsonic API. Navidrome relies upon it heavly all the time, there are basically no clients that dont rely on navidrome's own api due to compability reasons i assume.

**Why there is no reason that we need to wait for Subsonic's API changes?**
After researching the Link that got mentioned on the Githubs Readme turnts out there is no eta or any development on new subsonic api changes so there is basically no need to wait for future subsonic api changes.
Even if someone rebuilds it, it takes up months if not years due to how old subsonic is in some regards.
So i hope this gets fixed as fast as possible.

### PR DESCRIPTION
**Pull request by jeffvli**

### CODE REVIEW

**Comment by garfieldairlines** [comment]
Hello, just curious: any idea when this feature will be ready?
I kept using gonic until now but it's running Electron 22 that isn't really that supported anymore... I had a few problems with my package manager.

**Comment by iiPythonx** [comment]
> any idea when this feature will be ready?

Taken from jeffvli in discord (2 weeks ago):
> Here's my current plan before working on any subsonic support:
> 1. Upgrade to Mantine v7
> 2. Refactor the main app controller and api adapters for supported servers to better match what Subsonic supports.
> 3. Rewrite all the grid/table components. These make up a large part of the app itself and I'm not satisfied with how I initially wrote it which makes it difficult to make changes to anything around it.
> 
> With the above changes, the codebase should be able to support Subsonic (as well as other servers potentially).

As far as I know, he's focusing on the Mantine upgrade at the moment.

**Comment by garfieldairlines** [comment]
Wait, that vercel preview up above, I just tried it. It's working fine for me, it's what I need.
I want it so bad, I don't care if it's old or experimental, I'm almost begging you to release a version of this one specifically.

**Comment by iiPythonx** [comment]
You *could* build the subsonic branch from source and use that, although you'll be missing quite a lot of newer bug fixes and other changes (I believe the subsonic branch is based on 0.5.2).

**Comment by garfieldairlines** [comment]
Well the newer bug fixes and other changes aren't too important for me… I was using a unmaintained player for more than a year, again I'm drooling here in front of this pull request because sonixd isn't maintained anymore, and I kinda got stuck with my package manager (dependency hell because it's outdated as fuck).

**Comment by mattiasghodsian** [comment]
any ETA when subsonic branch gets some love ?

**Pull request closed without merging**
