### PR TITLE
add more emphasis to current song

### LINKED ISSUE #237: Highligh the current playing song more
## What do you want to be added?
Currently, only the text of the current song title is changed to blue. It should be more obvious which song is being played in the queue.

### PR DESCRIPTION
**Pull request by kgarner7**
closes #237; adds background and primary-color border

### CODE REVIEW

**Comment by jeffvli** [comment]
I'm not a fan of the border personally. It conflicts a bit with some other app borders such as when the queue it's in the sidebar.

I also want to enhance this with an animated play icon similar to Spotify's.

**Comment by kgarner7** [comment]
Fair enough! I was thinking about adding an indicator as well, but realized that would require another column. I can revert the border change and add a "now playing" column

**Comment by jeffvli** [comment]
I would say instead of a new column, it could be added to either:
- `row index` (replaces the number of the currently playing track)
- `title` or `title (combined)` (added to the right of the song name).

**Comment by kgarner7** [comment]
Row index _probably_ makes more sense, but if that is the choice, then it should probably be included by default in the full-screen play queue.

**Pull request merged**
